id: AD4EDAA8F
title: Taking the Vows of Sojong
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:52:17.644336
  last_modified_at: 2022-03-01 05:52:17.644363
