id: AD4EDAA8F
title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying (Sojong)
  the Three Sets of Vows'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:52:17.649210
  last_modified_at: 2022-03-01 05:52:17.649213
