id: AD4EDAA8F
title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day Vows of
  a Lay Practitioner'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:52:17.646907
  last_modified_at: 2022-03-01 05:52:17.646911
